apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
  namespace: nextcloud
data:
  my.cnf: |
    [mysqld]
    server-id=2
    relay-log=relay-bin
    log_bin=mysql-bin
    read_only=1
    innodb_buffer_pool_size=256M
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    skip-name-resolve
    max_connections=100
    bind-address=0.0.0.0
    innodb_flush_log_at_trx_commit=2
    sync_binlog=0
    skip-host-cache
    skip-slave-start
    
    [client]
    default-character-set=utf8mb4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  namespace: nextcloud
spec:
  serviceName: mysql-slave
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      initContainers:
      - name: wait-for-master
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "等待MySQL Master服务..."
          echo "MySQL Master服务: mysql-master"
          
          # 检查DNS解析
          echo "检查DNS解析..."
          nslookup mysql-master
          
          # 检查端口连通性
          echo "检查MySQL端口(3306)..."
          until nc -z mysql-master 3306; do
            echo "等待MySQL Master端口就绪..."
            sleep 5
          done
          echo "MySQL Master端口已开放!"
          
          # 额外等待确保MySQL完全启动
          sleep 10
          echo "初始化等待完成"
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin -h 127.0.0.1 -uroot -ppassword ping
          failureThreshold: 60
          periodSeconds: 10
        livenessProbe:
          exec:
            command: 
            - sh
            - -c
            - mysqladmin -h 127.0.0.1 -uroot -ppassword ping
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: 
            - sh
            - -c
            - mysql -h 127.0.0.1 -uroot -ppassword -e "SELECT 1"
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
      volumes:
      - name: config
        configMap:
          name: mysql-slave-config
      - name: data
        persistentVolumeClaim:
          claimName: mysql-slave-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: nextcloud
spec:
  clusterIP: None  # Headless 服务
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: mysql-slave
  publishNotReadyAddresses: true
